[package]
name = "processing_local_alignments"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "0.10.0"
clap = {version = "3.2.22", features = ["derive"]}
assert_fs = "1.0"
